// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmglnaxtpkrccabxrnku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZ2xuYXh0cGtyY2NhYnhybmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTMyMzcsImV4cCI6MjA2NTU2OTIzN30.o2MK7Uy42Ue1qQbpaA6F5bppwrbsGjeATcL60GUxXrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);